### ISSUE TITLE
Jbuilder expected file extensions

### ISSUE THREAD

**Issue by bpinto** [milkcocoa/grape-jbuilder#2]
The default file extension is `.json.jbuilder` but this gem is expecting to be used `.jbuilder`.

When using partials though, you have to use `.json.jbuilder`.
So, your folder will look like this:

```
app/views/api/
├── _appointment.json.jbuilder
└── appointments.jbuilder
```

**Comment by milkcocoa** [comment]
@bpinto Where is officially mentioned that the default file extension is `.json.jbuilder`?

I think if you want to use `.json.jbuilder`, you can use it in the `partial!` method like the following.

```
json.partial! 'appointment.json'
```

**Comment by bpinto** [comment]
I don't want to use .json.jbuilder, I want a pattern. Right now I have to use both.
The pattern jbuilder uses is .json.jbuilder so I don't see why run away from it.
