### ISSUE TITLE
Cannot use url helpers

### ISSUE THREAD

**Issue by bpinto** [milkcocoa/grape-jbuilder#3]
appointments.jbuilder:

```
json.link root_url
```

`{"error":"undefined local variable or method `root_url' for #<Grape::Endpoint:0x007ff5640423b8>"}`

**Comment by milkcocoa** [comment]
@bpinto I think this problem isn't due to this gem.
Check this! https://github.com/intridea/grape/wiki/Grape-and-Rails-Path-Helpers

**Comment by bpinto** [comment]
You are right! Thanks!
